Implement JWT Security
DEz-1996/online-book-store pull request #11
Opened 2023-12-24 20:29 UTC by DEz-1996

2023-12-26 13:11 UTC, andrii-hoienko requested changes

2023-12-26 13:11 UTC, andrii-hoienko commented on src/main/java/online/book/store/controller/AuthenticationController.java
> +    public UserLoginResponceDto login(@RequestBody UserLoginRequestDto requestDto) {
Looks like you forget to add @Valid annotation

2023-12-26 13:11 UTC, andrii-hoienko commented on src/main/java/online/book/store/dto/UserLoginRequestDto.java
> +        @Email
Password should be validated as email?

2023-12-26 13:11 UTC, andrii-hoienko commented on src/main/java/online/book/store/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant, then you will be able to get rid of BEARER_START_INDEX_TOKEN constant, becasue 7 is the length of "Bearer " string

2023-12-27 15:32 UTC, vovasalyha approved these changes
GJ, but pay attention to commit messages. `Some fixes with mentor's advice` is not very informative.

2023-12-30 01:52 UTC, merged