Add implementation for Orders:
DEz-1996/online-book-store pull request #15
Opened 2024-01-03 23:40 UTC by DEz-1996

1. Add Order.java and OrderItem.java entities
2. Add change files for liquibase
3. Add OrderService.java with OrderServiceImpl.java
4. Add dtos: OrderStatusRequestDto.java, OrderResponseDto.java, OrderItemResponseDto.java, OrderCreateRequestDto.java
5. Add OrderController.java
6. Add mappers: OrderMapper.java and OrderItemMapper.java
7. Add repositories: OrderRepository.java and OrderItemRepository.java

2024-01-04 13:44 UTC, annton-shakur approved these changes
Good job! i have noticed just a few minor things

2024-01-04 13:44 UTC, annton-shakur commented on src/main/java/online/book/store/controller/OrderController.java
> +@Tag(name = "Orders management", description = "Endpoints for mapping orders")
"Endpoints for mapping orders" -> "Endpoints for managing orders"

2024-01-04 13:44 UTC, annton-shakur commented on src/main/java/online/book/store/service/imp/OrderServiceImpl.java
> +    @Override
I believe that @Transactional annotation is needed here to provide atomicity

2024-01-04 13:44 UTC, annton-shakur commented on src/main/resources/db/changelog/changes/07-create_shopping_carts_table.yaml
> +                    nullable: false
nullable is redundant here as you have primary key constraint, but that's a minor thing

2024-01-04 13:44 UTC, annton-shakur commented on src/main/resources/db/changelog/changes/08-create_cart_items_table.yaml
> +                    nullable: false
nullable is redundant here as you have primary key constraint, but that's a minor thing

2024-01-05 10:12 UTC, d1sam requested changes
good job, but there are some changes should be done!

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/dto/order/OrderStatusRequestDto.java
> +    private Order.Status status;
```suggestion
    @NotNull
    private Order.Status status;
```

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/model/Order.java
> +        }
can be replaced with Stream API.

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/model/Order.java
> +    @ManyToOne
try to avoid EAGER relations.

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/model/OrderItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/repository/order/OrderItemRepository.java
> +    public List<OrderItem> findAllByOrderId(Long orderId);
```suggestion
    List<OrderItem> findAllByOrderId(Long orderId, Pageable pageable);
```
don't forget about `Pageable`

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/repository/order/OrderRepository.java
> +    Set<Order> findAllByUserId(Long userId);
```suggestion
    List<Order> findAllByUserId(Long userId, Pageable pageable);
```
don't forget about `Pageable`

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/service/imp/OrderServiceImpl.java
> +    public OrderResponseDto setStatus(OrderStatusRequestDto statusRequestDto, Long orderId) {
```suggestion
    @Override
    @Transactional
    public OrderResponseDto updateStatus(OrderStatusRequestDto statusRequestDto, Long orderId) {
```

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/service/imp/OrderServiceImpl.java
> +    public OrderResponseDto createOrder(OrderCreateRequestDto createRequestDto, User user) {
please divide logic to smaller private methods.

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/service/imp/OrderServiceImpl.java
> +                .collect(Collectors.toSet());
```suggestion
        return orderItemMapper.toDtoList(orderItems);
```
try to use method annotated by `@IterableMapping`

2024-01-05 10:12 UTC, d1sam commented on src/main/java/online/book/store/service/imp/OrderServiceImpl.java
> +                .map(orderMapper::toDto)
also use `@IterableMapping`

2024-01-05 15:23 UTC, vovasalyha approved these changes

2024-01-05 15:25 UTC, merged