Add spring tests(ShoppingCart entity):
DEz-1996/online-book-store pull request #19
Opened 2024-01-09 21:24 UTC by DEz-1996

Add tests for ShoppingCart entity:
1. ShoppingCartServiceImplTest.java
2. ShoppingCartRepositoryTest.java
3. ShoppingCartControllerTest.java

2024-01-10 07:20 UTC, TarasYurkovskyi approved these changes
Good job!

2024-01-10 08:39 UTC, yevheniisynytsia requested changes
Well done! Some style comments left

2024-01-10 08:39 UTC, yevheniisynytsia commented on src/test/java/online/book/store/controller/ShoppingCartControllerTest.java
> +            "classpath:database/cart_items/delete-all-cart-items.sql",
```suggestion
            "classpath:database/cart/items/delete-all-cart-items.sql",
```
you can google standards of naming packages in java projects. If I'm not mistaken it is recommended to have 1 word for a package, but not `_`

2024-01-10 08:39 UTC, yevheniisynytsia commented on src/test/java/online/book/store/repository/ShoppingCartRepositoryTest.java
> +    private static final String CANT_FIND_BOOK_BY_ID_MSG = "Can't find book by id: ";
unused

2024-01-10 08:39 UTC, yevheniisynytsia commented on src/test/java/online/book/store/repository/ShoppingCartRepositoryTest.java
> +                .setId(2L)
I would recommend moving id to constant and reuse it in `findByUserId` so that we can't misclick and look for user with id 3 and so on

2024-01-10 08:39 UTC, yevheniisynytsia commented on src/test/java/online/book/store/service/imp/ShoppingCartServiceImplTest.java
> +                .thenReturn(shoppingCartResponseDto);
```suggestion
                .thenReturn(shoppingCartResponseDto);
                
```

2024-01-11 11:48 UTC, yevheniisynytsia approved these changes
:fire:

2024-04-03 12:32 UTC, merged