Add project description to Readme file
DEz-1996/online-book-store pull request #20
Opened 2024-01-15 22:09 UTC by DEz-1996

2024-01-16 07:03 UTC, yevheniisynytsia requested changes
Great job! Let's add `how to tun the app` part!

2024-01-16 07:03 UTC, yevheniisynytsia commented on README.md
> +4. Security and JWT Tokens for User Auth: Security is paramount in our application. We've integrated Spring Security to safeguard your data and transactions. JWT (JSON Web Tokens) are employed for se
```suggestion
4. Security and JWT Tokens for User Auth: Security is paramount in our application. We've integrated Spring Security to safeguard your data and transactions. JWT (JSON Web Tokens) are employed for secure authentication and authorization, guaranteeing that only authorized users can access sensitive functionalities.
## Technologies used
```

2024-01-16 07:03 UTC, yevheniisynytsia commented on README.md
> +# Online Book Store
please add an instruction how to run the application locally

2024-01-19 08:04 UTC, d1sam approved these changes
well done!

2024-04-03 12:33 UTC, merged